=== Pokosteler/freeIT/src/lesson14/library/books.xsd
<?xml version="1.0"  standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="books.xsd">
    <element name="books">
        <complexType>
            <sequence>
                <element name="book" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name">
                                <simpleType>
                                    <restriction base="string">
                                        <maxLength value="40"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="author" type="string"/>
                            <element name="genres">
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="comedy"/>
                                        <enumeration value="tragedy"/>
                                        <enumeration value="drama"/>
                                        <enumeration value="horror"/>
                                        <enumeration value="novel"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="year" type="integer"/>
                            <element name="cover">
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="hardcover"/>
                                        <enumeration value="paperback"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="availableForReading" type="boolean"/>
                            <element name="outLibrary" type="boolean"/>
                            <element name="amount" type="integer"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== Pokosteler/freeIT/src/lesson14/library/books.xml
<?xml version="1.0" standalone="no"?>
<q:books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd"
         xmlns:q="books.xsd">
    <book>
        <name>Heart of a Dog</name>
        <author>Mikhail Bulgakov</author>
        <genres>novel</genres>
        <year>1925</year>
        <cover>paperback</cover>
        <availableForReading>true</availableForReading>
        <outLibrary>true</outLibrary>
        <amount>5</amount>
    </book>
    <book>
        <name>Green Mile</name>
        <author>Stephen King</author>
        <genres>horror</genres>
        <year>1996</year>
        <cover>hardcover</cover>
        <availableForReading>true</availableForReading>
        <outLibrary>false</outLibrary>
        <amount>3</amount>
    </book>
    <book>
        <name>The Great Gatsby</name>
        <author>F. Scott Fitzgerald</author>
        <genres>tragedy</genres>
        <year>1925</year>
        <cover>hardcover</cover>
        <availableForReading>false</availableForReading>
        <outLibrary>true</outLibrary>
        <amount>6</amount>
    </book>
</q:books>
