=== Pokosteler/freeIT/src/lesson13/devices.xsd
<?xml version="1.0"  standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="devices.xsd" xmlns:q="devices.xsd">
    <element name="Devices">
        <complexType>
            <sequence>
                <element name="Device" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="Name">
                                <simpleType>
                                    <restriction base="string">
                                        <maxLength value="40"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="Origin">
                                <simpleType>
                                    <restriction base="string">
                                        <maxLength value="40"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="Price" type="decimal"/>
                            <element name="Type" type="q:Type"/>
                            <element name="Critical" type="boolean"/>
                        </sequence>
                        <attribute name="id" type="q:id" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
    <simpleType name="id">
        <restriction base="ID">
            <pattern value="[a-zA-Z0-9]{6,8}"/>
        </restriction>
    </simpleType>
    <complexType name="Type">
        <sequence>
            <element name="Peripheral" type="boolean"/>
            <element name="PowerConsumption" type="decimal"/>
            <element name="CoolerAvailability" type="boolean"/>
            <element name="ComponentGroup" default="IO-Device">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="IO-Device"/>
                        <enumeration value="Multimedia"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="Ports" default="USB">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="COM"/>
                        <enumeration value="USB"/>
                        <enumeration value="LPT"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>
</schema>

=== Pokosteler/freeIT/src/lesson13/devices.xml
<?xml version="1.0" standalone="no"?>
<q:Devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="devices.xsd" xmlns:q="devices.xsd">
    <Device id="ds16326">
        <Name>Keyboard</Name>
        <Origin>Denmark</Origin>
        <Price>101</Price>
        <Type>
            <Peripheral>true</Peripheral>
            <PowerConsumption>12</PowerConsumption>
            <CoolerAvailability>false</CoolerAvailability>
            <ComponentGroup>IO-Device</ComponentGroup>
            <Ports>USB</Ports>
        </Type>
        <Critical>true</Critical>
    </Device>
</q:Devices>
        <!--Создать xml-файл, хранящий информацию об объектах предметной области ниже.
        Для валидации полученного xml-файла необходимо разработать соответствующую xsd схему.
        1. Общие требования:
         - Простые и комплексные типы
         - Шаблоны и предельные значения
         - Обязательно использование атрибутов и типа ID
         - Задание атрибутов по умолчанию
        2. Произвести проверку XML-документа с помощью XSD.
        3. Предметная область:
        Компьютерные комплектующие:
         - Name - название комплектующего
         - Origin - страна производства
         - Price - цена (0 - n USD)
         - Type (должно быть несколько)
         - периферийное либо нет, энергопотребление (ватт), наличие кулера( есть или нет),
         группа комплектующих (устройства ввода-вывода, мультимедийные), порты (COM, USB, LPT)
         - Critical - критично ли наличие комплектующего для работы компьютера.
        Корневой элемент назвать Devices-->
